kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: maven:3-jdk-11
    commands:
      - mvn -B -DskipTests clean package
      - mvn test -B
    volumes:
      - name: m2
        path: /root/.m2

  - name: archive-artifact
    image: alpine:latest
    commands:
      - mkdir -p /builds/libKonogonka
      - cp target/libKonogonka-*-jar-with-dependencies.jar /builds/libKonogonka/
    volumes:
      - name: builds
        path: /builds

  - name: install-local-repo
    image: maven:3-jdk-11
    commands:
      - . ./.deploy_locally
    volumes:
      - name: m2
        path: /root/.m2

volumes:
  - name: m2
    host:
      path: /home/docker/drone/files/m2
  - name: builds
    host:
      path: /home/www/builds